routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to(route('admin'));
});

Auth::routes();

Route::group(['prefix' => 'admin','middleware' => 'auth'], function (){
    Route::get('/','Admin\AdminController@index')->name('admin');
    Route::post('/updateData','Admin\AdminController@updateData')->name('updateData');
    Route::resource('user','Admin\UserController');
    Route::post('user/restore/{id}', 'Admin\UserController@restore')->name('user.restore');
    Route::get('order-request/search','Admin\OrderRequestController@search')->name('order-request.search');
    Route::resource('order-request','Admin\OrderRequestController');
    Route::get('order-request/{id}/detail','Admin\OrderRequestController@detail')->name('order-request.detail');


    Route::get('products','Admin\ProductController@index')->name('products.index');
    Route::get('suppliers','Admin\SupplierController@index')->name('suppliers.index');
    Route::get('order-request/{id}/approval','Admin\OrderRequestController@approval')->name('order-request.approval');
    Route::patch('order-request/{id}/approval','Admin\OrderRequestController@updateApproval');
    Route::get('order-request/{id}/supplier','Admin\OrderRequestController@supplier')->name('order-request.supplier');
    Route::post('order-request/{id}/supplier','Admin\OrderRequestController@addSupplier')->name('order-request.supplier-add');
    Route::get('order-request/{id}/supplier/edit','Admin\OrderRequestController@editSupplier')->name('order-request.supplier-edit');
    Route::post('order-request/{id}/supplier/edit','Admin\OrderRequestController@updateSupplier')->name('order-request.supplier-update');
    Route::get('order-request/{id}/supplier/detail','Admin\OrderRequestController@detailSupplier')->name('order-request.supplier-detail');

    Route::get('order-request/{id}/approval-supplier','Admin\OrderRequestController@approvalSupplier')->name('order-request.approval-supplier');
    Route::patch('order-request/{id}/approval-supplier','Admin\OrderRequestController@updateApprovalSupplier');

    Route::get('order-request/{id}/order','Admin\OrderRequestController@order')->name('order-request.order');
    Route::post('order-request/{id}/order-create','Admin\OrderRequestController@orderCreate')->name('order-request.orderCreate');
    Route::get('order-request/{id}/order/{order_id}/edit','Admin\OrderRequestController@editOrder')->name('order-request.order-edit');
    Route::get('order-request/{id}/order/{order_id}/detail','Admin\OrderRequestController@detailOrder')->name('order-request.order-detail');
    Route::post('order-request/{id}/order/{order_id}','Admin\OrderRequestController@updateOrder')->name('order-request.order-update');
    Route::get('order-request/{id}/order-approver/{order_id}','Admin\OrderRequestController@orderApproval')->name('order-request.approval-order');
    Route::patch('order-request/{id}/order-approver/{order_id}','Admin\OrderRequestController@updateOrderApproval');

    Route::get('order-request/{id}/print','Admin\OrderRequestController@printOrder')->name('order-request.order-print');

     Route::get('order-request/{id}/accountant','Admin\AccountantController@accountant')->name('order-request.accountant');
     Route::get('accountant','Admin\AccountantController@index')->name('order-request.accountant_index');
     Route::post('accountant/getOrderRequestAccountant','Admin\AccountantController@getOrderRequestAccountant')->name('order-request.getOrderRequestAccountant');
     Route::post('accountant/actionAccountant','Admin\AccountantController@action')->name('order-request.actionAccountant');
     Route::patch('order-request/{id}/approval-accountant','Admin\AccountantController@approval')->name('order-request.approval-accountant');

    Route::get('order-request/{id}/approval-advance','Admin\AdvanceController@advance')->name('order-request.approval-advance');
    Route::patch('order-request/{id}/approval-advance','Admin\AdvanceController@approval')->name('order-request.approval-submit-advance');

     Route::post('order-request/{id}/selectAdvanceUser','Admin\OrderRequestController@selectAdvanceUser')->name('order-request.selectAdvanceUser');
    Route::get('order-request/{id}/advance','Admin\AccountantController@accountant')->name('order-request.accountant');


    Route::resource('approval','Admin\ApprovalController');
    Route::post('approval/actionApprover','Admin\ApprovalController@actionApprover');

    Route::resource('images','Admin\ImageController');

    Route::post('/order-request/getOrderRequest', 'Admin\OrderRequestController@getOrderRequest');
    Route::post('/approval/getOrderRequestApproval', 'Admin\ApprovalController@getOrderRequestApproval');

    Route::get('notify', 'Admin\NotifyController@index')->name('notify.index');

    Route::post('supplier/history','Admin\SupplierController@history')->name('supplier.history');
    Route::post('product/history','Admin\ProductController@history')->name('product.history');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Order extends Model
{
    protected $table = "orders";
    protected $fillable = [
        "code",
        "order_request_id",
        "supplier_id",
        "supplier_code",
        "supplier_name",
        "country",
        "area",
        "phone1",
        "address1",
        "contact_person",
        "fax",
        "email",
        "total_cost",
        "status",
        "create_user_id"
    ];
    const STATUS_CREATED = "created";
    const STATUS_APPROVER = 'approved';
    const STATUS_REJECT = 'rejected';

    public static function setCode(){
        $max = Order::query()->max('id') + 1;
        return "OD".Date("Ym").'_'.sprintf( "%06d", $max);
    }

    public function details(){
        return $this->hasMany('App\Models\OrderDetail','order_id','id');
    }

    public function created_by(){
        return $this->belongsTo('App\Models\User','create_user_id','id');
    }

    public function supplier(){
        return $this->belongsTo('App\Models\OrderRequestSupplier','create_user_id','id');
    }

}

resources/views/admin/order/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Order
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Order</a></li>
        </ol>
    </section>
    @include('admin.layouts.notify')
    <!-- Main content -->
    <section class="content" id="app">
       <div class="row">
            <div class="col-md-12">
                <a class="btn btn-primary pull-right" href="{{route('order-request.search')}}"><i class="fa fa-plus"></i> Tạo mới</a>
            </div>
            <div class="col-md-12" style="margin-top: 10px">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Danh sách yêu cầu mua hàng</h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="table-response">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Mã yêu cầu</th>
                                                <th>Người tạo</th>
                                                <th>Ngày tạo</th>
                                                <th>Trạng thái</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr v-for="item,index in order_requests">
                                                <td>@{{ (pagination.current -1)*10 + index+1 }}</td>
                                                <td>@{{ item.code }}</td>
                                                <td>@{{ item.user.name }}</td>
                                                <td>@{{ item.created_at | dd-mm-yyyy }}</td>
                                                <td>@{{ item.status }}</td>
                                                <td>
                                                    <a class="btn btn-sm btn-primary" :href="'/admin/order-request/'+item.id">Chi tiết</a>
                                                    <!-- <a class="btn btn-sm btn-warning" :href="'/admin/order-request/'+item.id+'/edit'">Chỉnh sửa</a> -->
                                                    <!-- <button class="btn btn-sm btn-danger">Xóa</button> -->
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-md-12 " style="text-align: right">
                                <pagination v-model="pagination.page" :total="pagination.total" :current="pagination.current"></pagination>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            
        </div>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>

</div>
@endsection
@section('js')
    <script >
        var app = new Vue({
            el: '#app',
            data: {
                order_requests : <?php echo json_encode($order_requests); ?>,
                pagination: {
                    page: 1,
                    current:1,
                    total_records:<?php echo json_encode($total_records); ?>,
                    total:<?php echo json_encode($total); ?>
                }
            },
            methods:{
                load: function(){
                    var vm = this;
                    $.post('/admin/order-request/getOrderRequest', {page: vm.pagination.page}, function(res){
                        if(res.success){
                            vm.order_requests = res.order_requests
                            vm.pagination.current = res.page
                            vm.pagination.total = res.total
                            vm.pagination.total_records = res.total_records
                        }
                    })
                }
            },
            watch: {
                'pagination.page': function(){
                    this.load();
                }
            }
        })
    </script>
@endsection

resources/views/admin/order/order.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Create Order
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Order</a></li>
            <li class="active">Create</li>
        </ol>
    </section>
    @include('admin.layouts.notify')
    <!-- Main content -->
    <section class="content" id="app">
        <div class="row">
            <div class="col-xs-12">
                <a class="btn btn-success pull-right" @click="submit()" ><i class="fa fa-check"></i> Create</a>
            </div>
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="col-xs-12 col-md-8">
                <section class="box box-order">
                    <!-- title row -->
                    <div class="box-header with-border">
                        <h3 class="box-title">Nhà cung cấp</h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <p>
                                    <b>Mã:</b> @{{ form.order.supplier_code }}
                                </p>
                                <p>
                                    <b>Tên:</b> @{{ form.order.supplier_name }}
                                </p>
                                <p>
                                    <b>Đất nước</b> @{{ form.order.country }}
                                </p>
                                <p>
                                    <b>Địa chỉ:</b> @{{ form.order.address1 }}
                                </p>
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <p>
                                    <b>Người liên hệ:</b> @{{ form.order.contact_person }}
                                </p>
                                <p>
                                    <b>Số điện thoại:</b> @{{ form.order.phone1 }}
                                </p>
                                <p>
                                    <b>Fax:</b> @{{ form.order.fax }}
                                </p>
                                <p>
                                    <b>Email:</b> @{{ form.order.email }}
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="box box-order">
                    <!-- title row -->
                    <div class="box-header with-border">
                        <h3 class="box-title">Đơn hàng </h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th></th>
                                                <th>Mã sản phẩm</th>
                                                <th>Tên sản phẩm</th>
                                                <th>Đơn vị</th>
                                                <th>Số lượng</th>
                                                <th>Đơn giá</th>
                                                <th>Thành tiền</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr v-for="item,index in supplier.details">
                                                <td>@{{index+1}}</td>
                                                <td>
                                                    <div class="box-item-image">
                                                        <img v-if="!item.request_detail.path" src="{{ asset('images/empty.jpg') }}" width="100%">
                                                        <img v-else :src="item.request_detail.path" width="100%" alt="">
                                                    </div>
                                                </td>
                                                <td>@{{ item.request_detail.product_id }}</td>
                                                <td>@{{ item.request_detail.product_name }}</td>
                                                <td>@{{item.request_detail.unit}}</td>
                                                <td width="150">
                                                    @{{ item.request_detail.quantity | money }}
                                                </td>
                                                <td width="150">
                                                    <money class="form-control" v-model="item.price"></money>
                                                </td>
                                                
                                                <td class="text-right">@{{ item.request_detail.quantity * item.price | money }}</td>
                                            </tr>
                                        </tbody>
                                        <tfoot style="font-weight: bold;">
                                            <tr>
                                                <th colspan="5"  class="text-right">TOTAL</th>
                                                <td colspan="1" >@{{ total_quantity | money}}</td>
                                                <td class="text-right" colspan="1"></td>
                                                <td colspan="1" class="text-right">@{{ total_money | money }}</td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-xs-12 col-md-4">
                <section class="box">
                    <!-- title row -->
                    <div class="box-header with-border">
                        <h3 class="box-title">Người kiểm duyệt</h3>
                    </div>
                    <div class="box-body" style="padding-bottom: 20px">
                        <div class="row">
                            <div class="col-xs-12">
                                <label for="">Users</label>
                                <select2 :options="users" style="width: 100%" class="form-control" :multiple="true" :search="true" v-model="form.approvers" placeholder="Chọn nhân viên"></select2>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 10px">
                            <div class="col-xs-12">
                                <table class="table">
                                    <tr v-for="item,index in approvers">
                                        <td>@{{index+1}}</td>
                                        <td>@{{item.name}}</td>
                                        <td>@{{item.email}}</td>
                                        <td>@{{item.phone}}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>

</div>
@endsection
@section('js')
    <script type="text/javascript" src="{{asset('resources/js/table-product.js')}}"></script>
    <script >
        var app = new Vue({
            el: '#app',
            data: {
                supplier: <?php echo json_encode($supplier); ?>,
                users: <?php echo json_encode($users); ?>,
                form:{
                    approvers:[],
                    order:{
                        supplier_id: '',
                        supplier_name: '',
                        supplier_address: '',
                        supplier_code: '',
                        supplier_date_of_supply: '',
                        supplier_person_name: '',
                        supplier_phone: '',
                        details: []
                    }
                }
            },
            methods:{
                submit: function(){
                    var vm = this;
                    if(this.form.approvers.length == 0){
                        helper.showNotification("Chưa chọn người kiểm duyệt","danger")
                        return
                    }
                    $.post('/admin/order-request/'+vm.supplier.order_request_id+'/order-create',this.form,function(res){
                        if(res.success){
                            location.href = '/admin/order-request/'+vm.supplier.order_request_id
                        }else{
                            var message = res.message ? res.message : 'Thực hiện thao tác không thành công !'
                            helper.showNotification(message)
                        }
                    });
                }
            },
            computed:{
                total_quantity: function(){
                    var total = 0;
                    this.form.order.details.forEach(function(item){
                        total += item.request_detail.quantity;
                    })
                    return total;
                },
                total_money: function(){
                    var total = 0;
                    this.form.order.details.forEach(function(item){
                        total += (item.price*item.request_detail.quantity);
                    })
                    return total;
                },
                approvers: function(){
                    var vm = this;
                    return this.users.filter(function(item){
                        return vm.form.approvers.indexOf(String(item.id)) >=0;
                    })
                },
            },
            mounted(){
                this.form.order = {
                    details:this.supplier.details,
                    supplier_id: this.supplier.id,
                    supplier_name: this.supplier.supplier_name,
                    country: this.supplier.country,
                    area: this.supplier.area,
                    address1: this.supplier.address1,
                    phone1: this.supplier.phone1,
                    supplier_code: this.supplier.supplier_code,
                    contact_person: this.supplier.contact_person,
                    email: this.supplier.email,
                    fax: this.supplier.fax,
                }
            }
        })
    </script>
@endsection

resources/views/admin/order/select.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Create Order
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Order</a></li>
            <li class="active">Create</li>
        </ol>
    </section>
    @include('admin.layouts.notify')
    <!-- Main content -->
    <section class="content" id="app">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tìm kiếm phiếu yêu cầu</h3>
                    </div>
                    <form class="box-body" method="get" action="{{ route('order-request.create') }}">
                        @csrf
                        <div class="row" style="padding-bottom: 20px;">
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <label for="">Mã phiếu</label>
                                <input type="text" class="form-control" name="code" placeholder="Ex: A000-00000000">
                            </div>
                        </div>
                        <div class="row mt-1">
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <button type="submit" class="btn btn-success pull-right">Search</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>

</div>
@endsection
@section('js')
    <script >
        var app = new Vue({
            el: '#app',
            data: {
                code: ''
            },
            methods:{
                
            },
            watch:{
                
            },
            computed:{
                
            },
            mounted(){
            }
        })
    </script>
@endsection