routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to(route('admin'));
});

Auth::routes();

Route::group(['prefix' => 'admin','middleware' => 'auth'], function (){
    Route::get('/','Admin\AdminController@index')->name('admin');
    Route::post('/updateData','Admin\AdminController@updateData')->name('updateData');
    Route::resource('user','Admin\UserController');
    Route::post('user/restore/{id}', 'Admin\UserController@restore')->name('user.restore');
    Route::get('order-request/search','Admin\OrderRequestController@search')->name('order-request.search');
    Route::resource('order-request','Admin\OrderRequestController');
    Route::get('order-request/{id}/detail','Admin\OrderRequestController@detail')->name('order-request.detail');


    Route::get('products','Admin\ProductController@index')->name('products.index');
    Route::get('suppliers','Admin\SupplierController@index')->name('suppliers.index');
    Route::get('order-request/{id}/approval','Admin\OrderRequestController@approval')->name('order-request.approval');
    Route::patch('order-request/{id}/approval','Admin\OrderRequestController@updateApproval');
    Route::get('order-request/{id}/supplier','Admin\OrderRequestController@supplier')->name('order-request.supplier');
    Route::post('order-request/{id}/supplier','Admin\OrderRequestController@addSupplier')->name('order-request.supplier-add');
    Route::get('order-request/{id}/supplier/edit','Admin\OrderRequestController@editSupplier')->name('order-request.supplier-edit');
    Route::post('order-request/{id}/supplier/edit','Admin\OrderRequestController@updateSupplier')->name('order-request.supplier-update');
    Route::get('order-request/{id}/supplier/detail','Admin\OrderRequestController@detailSupplier')->name('order-request.supplier-detail');

    Route::get('order-request/{id}/approval-supplier','Admin\OrderRequestController@approvalSupplier')->name('order-request.approval-supplier');
    Route::patch('order-request/{id}/approval-supplier','Admin\OrderRequestController@updateApprovalSupplier');

    Route::get('order-request/{id}/order','Admin\OrderRequestController@order')->name('order-request.order');
    Route::post('order-request/{id}/order-create','Admin\OrderRequestController@orderCreate')->name('order-request.orderCreate');
    Route::get('order-request/{id}/order/{order_id}/edit','Admin\OrderRequestController@editOrder')->name('order-request.order-edit');
    Route::get('order-request/{id}/order/{order_id}/detail','Admin\OrderRequestController@detailOrder')->name('order-request.order-detail');
    Route::post('order-request/{id}/order/{order_id}','Admin\OrderRequestController@updateOrder')->name('order-request.order-update');
    Route::get('order-request/{id}/order-approver/{order_id}','Admin\OrderRequestController@orderApproval')->name('order-request.approval-order');
    Route::patch('order-request/{id}/order-approver/{order_id}','Admin\OrderRequestController@updateOrderApproval');

    Route::get('order-request/{id}/print','Admin\OrderRequestController@printOrder')->name('order-request.order-print');

     Route::get('order-request/{id}/accountant','Admin\AccountantController@accountant')->name('order-request.accountant');
     Route::get('accountant','Admin\AccountantController@index')->name('order-request.accountant_index');
     Route::post('accountant/getOrderRequestAccountant','Admin\AccountantController@getOrderRequestAccountant')->name('order-request.getOrderRequestAccountant');
     Route::post('accountant/actionAccountant','Admin\AccountantController@action')->name('order-request.actionAccountant');
     Route::patch('order-request/{id}/approval-accountant','Admin\AccountantController@approval')->name('order-request.approval-accountant');

    Route::get('order-request/{id}/approval-advance','Admin\AdvanceController@advance')->name('order-request.approval-advance');
    Route::patch('order-request/{id}/approval-advance','Admin\AdvanceController@approval')->name('order-request.approval-submit-advance');

     Route::post('order-request/{id}/selectAdvanceUser','Admin\OrderRequestController@selectAdvanceUser')->name('order-request.selectAdvanceUser');
    Route::get('order-request/{id}/advance','Admin\AccountantController@accountant')->name('order-request.accountant');


    Route::resource('approval','Admin\ApprovalController');
    Route::post('approval/actionApprover','Admin\ApprovalController@actionApprover');

    Route::resource('images','Admin\ImageController');

    Route::post('/order-request/getOrderRequest', 'Admin\OrderRequestController@getOrderRequest');
    Route::post('/approval/getOrderRequestApproval', 'Admin\ApprovalController@getOrderRequestApproval');

    Route::get('notify', 'Admin\NotifyController@index')->name('notify.index');

    Route::post('supplier/history','Admin\SupplierController@history')->name('supplier.history');
    Route::post('product/history','Admin\ProductController@history')->name('product.history');
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>AdminLTE 2 | Invoice</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="{{asset('resources/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{{asset('resources/bower_components/font-awesome/css/font-awesome.min.css')}}">
        <!-- Ionicons -->
        <link rel="stylesheet" href="{{asset('resources/bower_components/Ionicons/css/ionicons.min.css')}}">
        <link rel="stylesheet" href="{{asset('resources/bower_components/select2/dist/css/select2.min.css')}}">
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
        <link rel="stylesheet" href="{{asset('resources/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
        <!-- Theme style -->
        <link rel="stylesheet" href="{{asset('resources/dist/css/AdminLTE.min.css')}}">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
            folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
        <link rel="stylesheet" href="{{asset('resources/dist/css/skins/_all-skins.min.css')}}">
        <link rel="stylesheet" href="{{asset('resources/css/style.css')}}">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <link rel="stylesheet" href="{{asset('css/app.css')}}">
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            @include('admin.layouts.header')
            <!-- Left side column. contains the logo and sidebar -->
            @include('admin.layouts.sidebar')
            <!-- Content Wrapper. Contains page content -->
            @yield('content')
            <!-- /.content-wrapper -->
            @include('admin.layouts.footer')
        </div>
        <!-- ./wrapper -->
        <!-- jQuery 3 -->
        <script src="{{asset('resources/bower_components/jquery/dist/jquery.min.js')}}"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="{{asset('resources/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
        <script src="{{asset('resources/bower_components/moment/min/moment.min.js')}}"></script>
        <script src="{{asset('resources/bower_components/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
        <!-- FastClick -->
        <script src="{{asset('resources/bower_components/fastclick/lib/fastclick.js')}}"></script>
        <script src="{{asset('resources/bower_components/select2/dist/js/select2.full.min.js')}}"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <!-- AdminLTE App -->
        <script src="{{asset('resources/dist/js/adminlte.min.js')}}"></script>
        <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="{{asset('resources/dist/js/demo.js')}}"></script>
        <script src="{{asset('resources/plugins/notify/bootstrap-notify.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue"></script>
        <script src="{{asset('resources/js/v-money.js')}}"></script>
        <script src="{{asset('resources/js/helper.js')}}"></script>
        <script src="{{asset('resources/js/components.js')}}"></script>
        <script>
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $(function () {
                Vue.config.devtools = true
            })
            
        </script>
        @yield('js')
    </body>
</html>

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer no-print">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.18
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
    reserved.
</footer>

resources/views/admin/layouts/header.blade.php
<style>
    .user-image{
        border-radius: 50%;
        line-height: 25px;
        text-align: center;
        background: #fff;
        color: #3c8dbc;
        font-size: 20px;
        font-weight: bold;
        text-transform: uppercase;
    }
</style>
<header class="main-header">
    <!-- Logo -->
    <a href="/admin" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>TL</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>TechLink</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="user-image">{{ substr(Auth::user()->name,0,1) }}</span>
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu" style="width: auto">
                        
                        <li class="">
                            <form action="{{ route('logout') }}" method="POST" >
                                @csrf
                                <button style="width: 100%" type="submit" class="btn btn-default btn-flat">Sign out</button>
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/notify.blade.php
@if($errors->any())
	<div class="pad margin no-print">
	    <div class="callout callout-danger" style="margin-bottom: 0!important;">
	        <h4><i class="fa fa-info"></i> Note:</h4>
	        <ul>
	        @foreach ($errors->all() as $error)
		        <li>{{ $error }}</li>
		    @endforeach
			</ul>
	    </div>
	</div>
@endif
@if (\Session::has('message'))
   <div class="pad margin no-print">
	    <div class="callout callout-success" style="margin-bottom: 0!important;">
	    	<div>{{ Session::get('message') }}</div>
	    </div>
	</div>
@endif

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="">
                <a  href="{{route('admin')}}">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
                </span>
                </a>
            </li>
            @if(Auth::user()->role_id ==  \App\Models\User::ROLE_ADMIN)
            <li class="treeview">
                <a href="#">
                <i class="fa fa-user"></i> <span>Nhân sự</span>
                <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('user.index')}}"><i class="fa fa-circle-o"></i> Danh sách</a></li>
                    <li><a href="{{route('user.create')}}"><i class="fa fa-circle-o"></i> Tạo mới</a></li>
                </ul>
            </li>
            @endif
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-user"></i> <span>Phiếu YCMH</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('order-request.index')}}"><i class="fa fa-circle-o"></i> Danh sách</a></li>
                    <li><a href="{{route('order-request.search')}}"><i class="fa fa-circle-o"></i> Tạo mới</a></li>
                </ul>
            </li>
            @if(Auth::user()->role_id ==  \App\Models\User::ROLE_MANAGER)
            <li class="treeview" >
                <a href="#">
                    <i class="fa fa-user"></i> <span>Phiếu cần duyệt</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('approval.index',['step' => 1])}}"><i class="fa fa-circle-o"></i> Danh sách phiếu YCMH</a></li>
                    <li><a href="{{route('approval.index',['step' => 2])}}"><i class="fa fa-circle-o"></i> Danh sách phiếu chọn NCC</a></li>
                    <li><a href="{{route('approval.index',['step' => 4])}}"><i class="fa fa-circle-o"></i> Danh sách phiếu nâng cao</a></li>
                </ul>
            </li>
            @endif
            @if(Auth::user()->role_id == \App\Models\User::ROLE_ACCOUNTANT)
            <li class="" >
                <a href="{{route('order-request.accountant_index')}}">
                    <i class="fa fa-user"></i> <span>Kế toán</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
            </li>
            @endif
            @if(Auth::user()->role_id == \App\Models\User::ROLE_NOTIFY)
            <li class="">
                <a href="{{route('notify.index')}}">
                    <i class="fa fa-user"></i> <span>Tìm nhà cung cấp</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
            </li>
            @endif
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>