routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to(route('admin'));
});

Auth::routes();

Route::group(['prefix' => 'admin','middleware' => 'auth'], function (){
    Route::get('/','Admin\AdminController@index')->name('admin');
    Route::post('/updateData','Admin\AdminController@updateData')->name('updateData');
    Route::resource('user','Admin\UserController');
    Route::post('user/restore/{id}', 'Admin\UserController@restore')->name('user.restore');
    Route::get('order-request/search','Admin\OrderRequestController@search')->name('order-request.search');
    Route::resource('order-request','Admin\OrderRequestController');
    Route::get('order-request/{id}/detail','Admin\OrderRequestController@detail')->name('order-request.detail');


    Route::get('products','Admin\ProductController@index')->name('products.index');
    Route::get('suppliers','Admin\SupplierController@index')->name('suppliers.index');
    Route::get('order-request/{id}/approval','Admin\OrderRequestController@approval')->name('order-request.approval');
    Route::patch('order-request/{id}/approval','Admin\OrderRequestController@updateApproval');
    Route::get('order-request/{id}/supplier','Admin\OrderRequestController@supplier')->name('order-request.supplier');
    Route::post('order-request/{id}/supplier','Admin\OrderRequestController@addSupplier')->name('order-request.supplier-add');
    Route::get('order-request/{id}/supplier/edit','Admin\OrderRequestController@editSupplier')->name('order-request.supplier-edit');
    Route::post('order-request/{id}/supplier/edit','Admin\OrderRequestController@updateSupplier')->name('order-request.supplier-update');
    Route::get('order-request/{id}/supplier/detail','Admin\OrderRequestController@detailSupplier')->name('order-request.supplier-detail');

    Route::get('order-request/{id}/approval-supplier','Admin\OrderRequestController@approvalSupplier')->name('order-request.approval-supplier');
    Route::patch('order-request/{id}/approval-supplier','Admin\OrderRequestController@updateApprovalSupplier');

    Route::get('order-request/{id}/order','Admin\OrderRequestController@order')->name('order-request.order');
    Route::post('order-request/{id}/order-create','Admin\OrderRequestController@orderCreate')->name('order-request.orderCreate');
    Route::get('order-request/{id}/order/{order_id}/edit','Admin\OrderRequestController@editOrder')->name('order-request.order-edit');
    Route::get('order-request/{id}/order/{order_id}/detail','Admin\OrderRequestController@detailOrder')->name('order-request.order-detail');
    Route::post('order-request/{id}/order/{order_id}','Admin\OrderRequestController@updateOrder')->name('order-request.order-update');
    Route::get('order-request/{id}/order-approver/{order_id}','Admin\OrderRequestController@orderApproval')->name('order-request.approval-order');
    Route::patch('order-request/{id}/order-approver/{order_id}','Admin\OrderRequestController@updateOrderApproval');

    Route::get('order-request/{id}/print','Admin\OrderRequestController@printOrder')->name('order-request.order-print');

     Route::get('order-request/{id}/accountant','Admin\AccountantController@accountant')->name('order-request.accountant');
     Route::get('accountant','Admin\AccountantController@index')->name('order-request.accountant_index');
     Route::post('accountant/getOrderRequestAccountant','Admin\AccountantController@getOrderRequestAccountant')->name('order-request.getOrderRequestAccountant');
     Route::post('accountant/actionAccountant','Admin\AccountantController@action')->name('order-request.actionAccountant');
     Route::patch('order-request/{id}/approval-accountant','Admin\AccountantController@approval')->name('order-request.approval-accountant');

    Route::get('order-request/{id}/approval-advance','Admin\AdvanceController@advance')->name('order-request.approval-advance');
    Route::patch('order-request/{id}/approval-advance','Admin\AdvanceController@approval')->name('order-request.approval-submit-advance');

     Route::post('order-request/{id}/selectAdvanceUser','Admin\OrderRequestController@selectAdvanceUser')->name('order-request.selectAdvanceUser');
    Route::get('order-request/{id}/advance','Admin\AccountantController@accountant')->name('order-request.accountant');


    Route::resource('approval','Admin\ApprovalController');
    Route::post('approval/actionApprover','Admin\ApprovalController@actionApprover');

    Route::resource('images','Admin\ImageController');

    Route::post('/order-request/getOrderRequest', 'Admin\OrderRequestController@getOrderRequest');
    Route::post('/approval/getOrderRequestApproval', 'Admin\ApprovalController@getOrderRequestApproval');

    Route::get('notify', 'Admin\NotifyController@index')->name('notify.index');

    Route::post('supplier/history','Admin\SupplierController@history')->name('supplier.history');
    Route::post('product/history','Admin\ProductController@history')->name('product.history');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use phpDocumentor\Reflection\Types\Self_;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;

    const ROLE_ADMIN = 1;
    const ROLE_USER = 2;
    const ROLE_NOTIFY = 3;
    const ROLE_ACCOUNTANT = 4;
    const ROLE_MANAGER = 5;
    const ROLE_SALES = 6;


    public static $roles = [
        self::ROLE_ADMIN => 'Admin',
        self::ROLE_USER => 'User',
        self::ROLE_NOTIFY => 'Purchasing ',
        self::ROLE_ACCOUNTANT => 'Accountant',
        self::ROLE_MANAGER => 'Manager',
        self::ROLE_SALES => 'Sales',
    ];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($this->checkAdmin()){
            $query = User::latest();
            if($request->get('is_delete') == 1){
                $query->onlyTrashed();
            }
            $users = $query->paginate(10);
            return view('admin.user.index',compact('users'));
        }
        return abort(403);
    }

    public function restore($id){
        $user = User::onlyTrashed()->where('id', $id)->first();
        if($user){
            $user->restore();
            flash('Khôi phục '.$user->name.' thành công');
            return redirect()->back();
        }else{
            return redirect()->back()->withErrors([
                'User not found'
            ]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if($this->checkAdmin()) {
            $roles = User::$roles;
            return view('admin.user.create', compact('roles'));
        }
        return abort(403);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
        public function store(UserCreateRequest $request)
    {
        if($this->checkAdmin()) {
            $data = $request->all();
            $data['password'] = bcrypt($data['password']);
            User::create($data);
            flash('Success');
            return redirect()->to(route('user.index'));
        }
        return abort(403);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if($this->checkAdmin()) {
            $user = User::find($id);
            if ($user) {
                $roles = User::$roles;
                return view('admin.user.edit', compact('user', 'roles', 'id'));
            }
            return abort('404');
        }
        return abort('403');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'password' => 'nullable|min:6'
        ]);
        if($validator->fails()){
            return redirect()->back()->withErrors($validator->errors());
        }
        if($this->checkAdmin()) {
            $data = $request->only(['name', 'role_id','password']);
            if(empty($data['password'])){
                unset($data['password']);
            }else{
                $data['password'] = bcrypt($data['password']);
            }
            $user = User::find($id);
            if ($user) {
                $user->update($data);
                flash('Cập nhật thông tin thành công');
                return redirect()->back();
            }
            return redirect()->back()->withErrors(['Thực hiện thao tác không thành công']);
        }
        return abort(403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if($this->checkAdmin()) {
            $user = User::find($id);
            if ($user) {
                $user->delete();
            }
            flash('Xóa thành công');
            return redirect()->back();
        }
        return abort(403);
    }

    public function checkAdmin(){
        return Auth::user()->role_id == User::ROLE_ADMIN;
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Create User
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">User</a></li>
            <li class="active">Create</li>
        </ol>
    </section>
    @include('admin.layouts.notify')
    <!-- Main content -->
    <section class="invoice">
        <!-- title row -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-globe"></i> Create User
                </h2>
            </div>
            <!-- /.col -->
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                {!! Form::open(['method' => 'POST', 'url' => route('user.store')]) !!}
                <div class="form-group">
                    {!! Form::label('name', 'Name') !!}
                    {!! Form::text('name' , null , ['class' => 'form-control','placeholder' => 'Name','required']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('email', 'Email') !!}
                    {!! Form::email('email' , null , ['class' => 'form-control','placeholder' => 'Email','required']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('role_id', 'Role') !!}
                    {!! Form::select('role_id', $roles,null,['class' => 'form-control']) !!} 
                </div>
                <div class="form-group">
                    {!! Form::label('password', 'Password') !!}
                    {!! Form::password('password', ['class' => 'form-control','placeholder' => 'Password']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('password_confirmation', 'Password Confirmation') !!}
                    {!! Form::password('password', ['class' => 'form-control','placeholder' => '','name' => 'password_confirmation']) !!}
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success pull-right"><i class="fa fa-check"></i> Create</button>
                        <a href="{{route('user.index')}}" class="btn btn-default pull-right" style="margin-right: 5px;" ><i class="fa fa-chevron-left"></i> Back</a>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Create User
        </h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('user.index') }}">User</a></li>
            <li class="active">Edit</li>
        </ol>
    </section>
    @include('admin.layouts.notify')
    <!-- Main content -->
    <section class="invoice">
        <!-- title row -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-globe"></i> Edit User
                </h2>
            </div>
            <!-- /.col -->
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                {!! Form::open(['method' => 'POST', 'url' => route('user.update', ['id' => $id])]) !!}
                @method('patch')
                <div class="form-group">
                    {!! Form::label('name', 'Name') !!}
                    {!! Form::text('name' , $user->name , ['class' => 'form-control','placeholder' => 'Name','required']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('email', 'Email') !!}
                    {!! Form::email('email' , $user->email , ['class' => 'form-control','placeholder' => 'Email','required','disabled']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('role_id', 'Role') !!}
                    {!! Form::select('role_id', $roles, $user->role_id ,['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('password', 'Password') !!}
                    <span class="text-danger">(*) Để trống nếu không muốn thay đổi password</span>
                    {!! Form::password('password', ['class' => 'form-control']) !!}
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success pull-right"><i class="fa fa-check"></i> Update</button>
                        <a href="{{route('user.index')}}" class="btn btn-default pull-right" style="margin-right: 5px;" ><i class="fa fa-chevron-left"></i> Back</a>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')
@section('content')
<style>
    .btn-dark{
        background-color: #3c3c3c;
        color: #fff;
    }
    .btn-dark:hover{
        background-color: #3c3c3c !important;
        color: #fff !important;
    }
</style>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Create User
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">User</a></li>
        </ol>
    </section>
    @include('admin.layouts.notify')
    <!-- Main content -->

    <section class="invoice">
        <!-- title row -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-globe"></i> List User
                </h2>

            </div>
            <!-- /.col -->
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-8">
                Result: <b>{{$users->total()}} </b>
            </div>
            <div class="col-xs-12 col-md-4">
                <a class="btn btn-success pull-right" href="{{route('user.create')}}"><i class="fa fa-plus"></i> Create</a>
            </div>
        </div>
        <div class="row mt-10">
            <div class="col-xs-12 text-right">
                <div class="btn-group">
                    @if(isset($_GET['is_delete']) && $_GET['is_delete'] == 1)
                        <a class="btn btn-default " href="{{ route('user.index') }}"><i class="fa fa-bars" aria-hidden="true"></i></a>
                        <button class="btn btn-default btn-dark" disabled><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                    @else
                        <button class="btn btn-default btn-dark" disabled><i class="fa fa-bars" aria-hidden="true"></i></button>
                        <a class="btn btn-default" href="{{ route('user.index', ['is_delete' => 1]) }}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                    @endif
                    
                    
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td>{{$loop->index  +1}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{ \App\Models\User::$roles[$user->role_id] }}</td>
                                <td width="200">
                                    @if(isset($_GET['is_delete']) && $_GET['is_delete'] == 1)
                                    <form method="POST" class="form-inline" action="{{ route('user.restore', ['id' => $user->id]) }}">
                                        @csrf
                                        <input type="hidden" name="id" value="{{$user->id}}">
                                        <button class="btn btn-primary" type="submit">Khôi phục</button>
                                    </form>
                                    @else
                                    <a class="btn btn-warning" href="{{route('user.edit', ['id' => $user->id])}}">Edit</a>
                                    <form method="POST" class="form-inline" action="{{ route('user.destroy', ['id' => $user->id]) }}">
                                        @csrf
                                        @method('delete')
                                        <input type="hidden" name="id" value="{{$user->id}}">
                                        <button class="btn btn-danger" type="submit">Xóa</button>
                                    </form>
                                    @endif
                                    
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-xs-12 text-right">
                {{$users->links()}}
            </div>
        </div>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>
</div>
@endsection